database:
  connection:
    max_open_conns:  10
    max_idle_conns:  5
    conn_max_lifetime: 30m

logger:
  level: debug
  development: true
  disable_caller: true
  disable_stacktrace: true
  encoding: console
  output_paths: [stderr]
  error_output_paths: [stderr]

server:
  max_header_bytes:  1048576
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 120s